site_name: uv-workspace-dynamic-versioning
site_description: A powerful Hatch plugin for dynamic versioning and dependency injection in uv workspaces.
site_url: https://github.com/indiVar0508/uv-workspace-dynamic-versioning

theme:
  name: material
  icon:
    logo: material/parallax
  favicon: material/parallax
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/indiVar0508/uv-workspace-dynamic-versioning

plugins:
  - search
  - minify:
      minify_html: true
  - glightbox
  - git-revision-date-localized:
      fallback_to_build_date: true
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

nav:
  - Home: index.md
  - Guide:
    - Getting Started: usage.md
    - Configuration: configuration.md
  - Reference:
    - API: api.md
    - Changelog: CHANGELOG.md
    - Contributing: contributing_link.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
