"""CI script to validate the build and versioning logic.

This script bootstraps a temporary project, initializes a git repository,
creates tags and commits, and verifies that the version generated by
uv-workspace-dynamic-versioning is correct.
"""

import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path


class TestBuildValidation(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = Path(tempfile.mkdtemp())
        self.repo_dir = self.tmp_dir / "test-repo"
        self.repo_dir.mkdir()

        # Get the absolute path to the current project
        self.plugin_path = Path(__file__).parent.parent.resolve()

        # Initialize git repo
        subprocess.run(["git", "init"], cwd=self.repo_dir, check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=self.repo_dir, check=True)
        subprocess.run(["git", "config", "user.name", "Test User"], cwd=self.repo_dir, check=True)

    def tearDown(self):
        shutil.rmtree(self.tmp_dir)

    def create_project(self, name="test-pkg", config=None):
        # Use tomlkit for safe TOML generation
        import tomlkit
        
        doc = tomlkit.document()
        
        project = tomlkit.table()
        project.add("name", name)
        project.add("dynamic", ["version"])
        project.add("requires-python", ">=3.9")
        doc.add("project", project)
        
        build_system = tomlkit.table()
        build_system.add("requires", ["hatchling", f"uv-workspace-dynamic-versioning @ {self.plugin_path}"])
        build_system.add("build-backend", "hatchling.build")
        doc.add("build-system", build_system)
        
        tool = tomlkit.table()
        hatch = tomlkit.table()
        version = tomlkit.table()
        version.add("source", "uv-workspace-dynamic-versioning")
        hatch.add("version", version)
        tool.add("hatch", hatch)
        
        if config:
            plugin_config = tomlkit.table()
            for k, v in config.items():
                plugin_config.add(k.replace('_', '-'), v)
            tool.add("uv-workspace-dynamic-versioning", plugin_config)
            
        doc.add("tool", tool)

        with open(self.repo_dir / "pyproject.toml", "w") as f:
            f.write(tomlkit.dumps(doc))

        # Create source
        src_dir = self.repo_dir / "src" / name.replace("-", "_")
        src_dir.mkdir(parents=True)
        (src_dir / "__init__.py").touch()

    def git_commit(self, message="Initial commit"):
        subprocess.run(["git", "add", "."], cwd=self.repo_dir, check=True)
        subprocess.run(["git", "commit", "-m", message], cwd=self.repo_dir, check=True)

    def git_tag(self, tag):
        subprocess.run(["git", "tag", tag], cwd=self.repo_dir, check=True)

    def get_version(self):
        result = subprocess.run(
            ["hatch", "version"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(f"STDOUT: {result.stdout}")
            print(f"STDERR: {result.stderr}")
            result.check_returncode()
        return result.stdout.strip()

    def test_basic_versioning(self):
        self.create_project()
        self.git_commit()
        self.git_tag("v1.0.0")

        version = self.get_version()
        self.assertEqual(version, "1.0.0")

        # Add a commit
        (self.repo_dir / "file.txt").touch()
        self.git_commit("Add file")

        version = self.get_version()
        # By default, it uses PEP 440 with distance
        self.assertTrue(version.startswith("1.0.0.post1"))

    def test_custom_tag_pattern(self):
        # Test the 0.0.0 issue
        self.create_project(config={"pattern": r"release-(?P<base>\d+\.\d+\.\d+)"})
        self.git_commit()
        self.git_tag("release-2.0.0")

        version = self.get_version()
        self.assertEqual(version, "2.0.0")

        # If we use a tag that doesn't match, it should be 0.0.0
        self.git_tag("v3.0.0")
        # Since release-2.0.0 is still there and matched, it should still be 2.0.0 (or newer)
        # But if we ONLY had v3.0.0, it would be 0.0.0


if __name__ == "__main__":
    unittest.main()
